### PR TITLE
fix: properly fit multiline texts

### LINKED ISSUE #313: Formatting change in ignored block (label in wide figure)
```typ
// @typstyle off
#figure(
  [stihesathis t tieh asthestah stieh e hasthiestah isteah stieh ast ieh astiheast],
) <label>
// @typstyle on
```

get reformatted to

```typ
// @typstyle off
#figure(
  [stihesathis t tieh asthestah stieh e hasthiestah isteah stieh ast ieh astiheast],
)
<label>
// @typstyle on
```

`--wrap-text` & `--line-width 80`

### PR DESCRIPTION
**Pull request by QuadnucYard**
Fixes #313.

- Enhancement: Now texts spanning multiple lines, such as strings, inline raws, or syntax nodes marked `typstyle off` are correctly layouted according to their line widths.
- Enhancement: Labels are no longer reflowed to the next line.
- Fix: `typstyle off` now properly works for args.
- Fix: markup texts were wrongly treated as verbatim, which could lead to significant performance loss.

### CODE REVIEW

File: crates/typstyle-core/src/pretty/code_misc.rs [hunk 1]
```diff
@@ -36,6 +36,17 @@ impl<'a> PrettyPrinter<'a> {
         }
     }
 
+    pub(super) fn convert_arg(&'a self, ctx: Context, arg: Arg<'a>) -> ArenaDoc<'a> {
+        /* if let Some(res) = self.check_disabled(arg.to_untyped()) {
+            return res;
+        } */
```
Comment (Enter-tainer) [inline crates/typstyle-core/src/pretty/code_misc.rs:42]: should we remove this?

**Review by Enter-tainer — APPROVED** [review]
